"""SQLAlchemy schema definitions for the Farm Worker Management System.

This module is the single source of truth for the database schema.
`Workers.sql` is generated from these models by `tools/export_schema.py`
and must never be edited by hand.
"""

from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from database import db


class Setting(db.Model):
    """Key-value store for all system configuration.

    A single table rather than a column per setting, so a new option needs no
    migration. app.DEFAULT_SETTINGS seeds every key at startup.

    Examples of live rows:
        org_name              "Chisamba Green Farms"
        face_match_threshold  "35"        minimum match confidence, percent
        geofence_radius_m     "500"       metres from the farm centre
        napsa_rate            "0.05"      5 percent
        camera_index          "0"         the built-in camera fallback
    """
    __tablename__ = "settings"

    id = db.Column(db.Integer, primary_key=True)
    key = db.Column(db.String(100), unique=True, nullable=False)
    value = db.Column(db.Text, nullable=True)

    def __repr__(self):
        return f"<Setting {self.key}={self.value}>"


class User(db.Model):
    """Dashboard accounts. Workers do not have one - they clock in with a PIN.

    `role` is enforced in the routes via security.py, not merely reflected in
    the interface: "admin", "supervisor" or "viewer".

    `must_change_password` gates the whole dashboard until a new password is
    set, so a temporary or seeded password cannot be left in place. It is set
    on the seeded admin, on every account created by an administrator, and on
    every password reset.
    """
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    name = db.Column(db.String(120), nullable=True)
    email = db.Column(db.String(120), nullable=True)
    phone = db.Column(db.String(30), nullable=True)
    role = db.Column(db.String(30), default="supervisor", nullable=False)
    linked_worker_id = db.Column(db.Integer, db.ForeignKey("workers.id"), nullable=True)
    password_hash = db.Column(db.String(256), nullable=False)
    is_active = db.Column(db.Boolean, default=True, nullable=False)
    must_change_password = db.Column(db.Boolean, default=False, nullable=False)
    last_login_at = db.Column(db.DateTime, nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    def set_password(self, password: str) -> None:
        self.password_hash = generate_password_hash(password)

    def check_password(self, password: str) -> bool:
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return f"<User {self.username} ({self.role})>"


class AuditLog(db.Model):
    """Append-only record of who did what, when and from where.

    Written by app._log_audit on every mutation, including refused clock-ins.
    Examples of `action` values:
        login                    a sign-in, with the role in `details`
        worker.add               a worker was onboarded
        biometric.enroll         face samples were stored
        attendance.recorded      a verified punch
        attendance.rejected      a refused punch, with the reason
        payroll.generate         a week was calculated
    """
    __tablename__ = "audit_logs"

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=True)
    username = db.Column(db.String(80), nullable=False)
    action = db.Column(db.String(100), nullable=False)
    details = db.Column(db.Text, nullable=True)
    ip_address = db.Column(db.String(45), nullable=True)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)

    def __repr__(self):
        return f"<AuditLog {self.username} {self.action} @ {self.timestamp}>"


class Worker(db.Model):
    """A farm worker.

    Notable fields:
      worker_id    the human-facing code, a 4-digit sequence: "0001", "0002".
                   Generated by app._generate_worker_id, never typed in.
      pin_hash     hashed with Werkzeug. Write-only: it can be reset, never read.
      pin_fingerprint
                   SHA-256 of the PIN, used ONLY to enforce that no two workers
                   share a PIN. Despite the name this is not a biometric - the
                   biometric lives in FaceTemplate.
      fingerprint_template
                   reserved for a future fingerprint scanner. The project is
                   camera-only, so nothing writes it today.
      hourly_rate  feeds payroll. Blank falls back to default_hourly_rate in
                   Settings, e.g. 18.00 ZMW per hour.
      face_enrolled_at
                   set when the first sample is stored; cleared when samples
                   are wiped. A worker with no samples cannot clock in.
      status       "active", "inactive" or "suspended". Only active workers can
                   clock in or appear in payroll generation.
      card_barcode the value on the worker's scannable card. Its form depends
                   on the barcode_source setting; see barcode_engine.
    """
    __tablename__ = "workers"

    id = db.Column(db.Integer, primary_key=True)
    worker_id = db.Column(db.String(20), unique=True, nullable=False)
    name = db.Column(db.String(120), nullable=False)
    nrc_number = db.Column(db.String(20), unique=True, nullable=True)
    pin_hash = db.Column(db.String(256), nullable=False)
    pin_fingerprint = db.Column(db.String(64), nullable=True)
    fingerprint_template = db.Column(db.LargeBinary, nullable=True)
    phone_number = db.Column(db.String(30), nullable=True)
    address = db.Column(db.String(255), nullable=True)
    emergency_contact = db.Column(db.String(120), nullable=True)
    department = db.Column(db.String(80), nullable=True)
    hourly_rate = db.Column(db.Float, nullable=True)
    # Pay cycle for this worker: "weekly", "fortnightly", "semi-monthly" or
    # "monthly". NULL means "use the farm default in Settings", exactly as a
    # NULL hourly_rate falls back to default_hourly_rate. Farms commonly run
    # casual labour weekly and permanent staff monthly, so this has to be
    # settable per person rather than only farm-wide.
    payroll_period = db.Column(db.String(20), nullable=True)

    # --- Identity card ----------------------------------------------------
    # card_barcode is the value printed on the worker's card and read by the
    # scanner. What goes in it is a farm setting, not a fixed decision:
    #   nrc_plain   the NRC itself, readable by anyone who scans the card
    #   nrc_hash    a one-way scramble of the NRC; unique per person, but the
    #               NRC cannot be read back from it
    #   card_number a generated code that means nothing outside this system
    # See barcode_engine.card_value(). Unique so two workers can never share a
    # card, and nullable because a worker may not have been issued one yet.
    card_barcode = db.Column(db.String(64), unique=True, nullable=True)
    card_issued_at = db.Column(db.DateTime, nullable=True)
    # "active" or "void". A void card is refused at the capture point even
    # though the row survives, so a lost card can be retired without deleting
    # the history that references it.
    card_status = db.Column(db.String(20), default="active", nullable=True)

    face_enrolled_at = db.Column(db.DateTime, nullable=True)
    enrollment_date = db.Column(db.DateTime, default=datetime.utcnow)
    status = db.Column(db.String(20), default="active", nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    def set_pin(self, pin: str) -> None:
        self.pin_hash = generate_password_hash(pin)

    def check_pin(self, pin: str) -> bool:
        return check_password_hash(self.pin_hash, pin)

    def __repr__(self):
        return f"<Worker {self.worker_id} - {self.name}>"


class Attendance(db.Model):
    """One work session: a clock-in, and later a clock-out.

    An open session is a row with check_out_time NULL. A worker may have at most
    one, which is how "already clocked in" and "no open check-in" are detected.

    The two verification flags mean different things and are deliberately not
    merged - conflating them was a defect in the first release:
      verified_by_cctv  a snapshot was captured and linked to this session
      verified_by_face  the captured face MATCHED this worker's enrolled
                        template. This is the one that makes the record
                        attributable to a person.

    check_in_match_score / check_out_match_score
        match confidence as a percentage, higher is better, e.g. 71.79.
    within_geofence / distance_from_farm_m
        measured against the farm centre in Settings, e.g. False and 1218.4
        metres. Recorded on every punch; only refused when enforcement is on.
    """
    __tablename__ = "attendance"

    attendance_id = db.Column(db.Integer, primary_key=True)
    worker_id = db.Column(db.Integer, db.ForeignKey("workers.id"), nullable=False)
    check_in_time = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    check_out_time = db.Column(db.DateTime, nullable=True)
    latitude = db.Column(db.Float, nullable=True)
    longitude = db.Column(db.Float, nullable=True)
    # True when a CCTV snapshot was captured and linked to this session.
    verified_by_cctv = db.Column(db.Boolean, default=False, nullable=False)
    # True when the captured face matched this worker's enrolled template.
    verified_by_face = db.Column(db.Boolean, default=False, nullable=False)
    check_in_match_score = db.Column(db.Float, nullable=True)
    check_out_match_score = db.Column(db.Float, nullable=True)
    within_geofence = db.Column(db.Boolean, nullable=True)
    distance_from_farm_m = db.Column(db.Float, nullable=True)

    def __repr__(self):
        return f"<Attendance {self.attendance_id} worker={self.worker_id}>"


class CCTVFeed(db.Model):
    """A camera. Registering one here is what makes it watchable.

    rtsp_url is the live source in any of three forms:
        "rtsp://user:pass@192.168.1.50:554/stream1"  an IP camera
        "1"                                          a USB device index
        "builtin://0"                                this machine's own camera

    is_primary marks the ATTENDANCE camera - the one used for clock-in
    verification, snapshots and event clips. Every other feed is surveillance.
    """

    __tablename__ = "cctv_feeds"

    feed_id = db.Column(db.Integer, primary_key=True)
    camera_name = db.Column(db.String(50), nullable=False)
    camera_location = db.Column(db.String(100), nullable=True)
    rtsp_url = db.Column(db.String(255), nullable=True)
    status = db.Column(db.String(20), default="offline", nullable=False)
    is_primary = db.Column(db.Boolean, default=False, nullable=False)
    last_heartbeat = db.Column(db.DateTime, nullable=True)


class Payroll(db.Model):
    """One worker's pay for one week. All amounts in ZMW.

    computed_from_attendance distinguishes a row generated from recorded
    sessions from a hand-entered correction. Either way the amounts are
    calculated by payroll_engine.compute_pay - only hours and a rate are input.

    napsa_rate and nhima_rate store the rates ACTUALLY USED, so a payslip stays
    reproducible after the rates change in Settings.

    Example row: 42 hours of which 2 overtime at 20.00/hour ->
        gross 860.00, NAPSA 43.00, NHIMA 8.60, net 808.40
    """

    __tablename__ = "payroll"

    payroll_id = db.Column(db.Integer, primary_key=True)
    worker_id = db.Column(db.Integer, db.ForeignKey("workers.id"), nullable=False)
    # The last day of the period this row covers. The column is named
    # week_ending for history - it predates any period other than a week, and
    # the additive-only migration cannot rename a column - but it now means
    # "period ending" for every cycle.
    week_ending = db.Column(db.Date, nullable=False)
    # The first day of the period, and which cycle produced it. Both are
    # recorded on the ROW rather than only read from Settings, because a farm
    # that switches from weekly to monthly still has to be able to read last
    # year's payslips: without these, a list showing 875 next to 3,400 is
    # unreadable and a worker will think they were short-paid.
    period_start = db.Column(db.Date, nullable=True)
    period_type = db.Column(db.String(20), nullable=True)
    total_hours = db.Column(db.Float, nullable=True)
    overtime_hours = db.Column(db.Float, nullable=True)
    hourly_rate = db.Column(db.Float, nullable=True)
    overtime_pay = db.Column(db.Float, nullable=True)
    gross_pay = db.Column(db.Float, nullable=True)
    napsa_rate = db.Column(db.Float, nullable=True)
    nhima_rate = db.Column(db.Float, nullable=True)
    napsa_deduction = db.Column(db.Float, nullable=True)
    nhima_deduction = db.Column(db.Float, nullable=True)
    net_pay = db.Column(db.Float, nullable=True)
    computed_from_attendance = db.Column(db.Boolean, default=False, nullable=False)
    generated_at = db.Column(db.DateTime, nullable=True)
    paid_status = db.Column(db.String(20), default="pending", nullable=False)
    payment_date = db.Column(db.Date, nullable=True)

    __table_args__ = (
        db.UniqueConstraint("worker_id", "week_ending", name="uq_payroll_worker_week"),
    )


class BiometricDevice(db.Model):
    """Registry of enrolment and verification hardware.

    device_type defaults to "camera" because the project is camera-only; the
    "fingerprint" option is kept for a future scanner. This table is a record
    of what is installed where - the actual capture path goes through
    cctv_engine and the camera sources on the CCTV page.
    """

    __tablename__ = "biometric_devices"

    device_id = db.Column(db.Integer, primary_key=True)
    device_name = db.Column(db.String(50), nullable=False)
    device_serial = db.Column(db.String(100), unique=True, nullable=True)
    device_type = db.Column(db.String(20), default="camera", nullable=False)
    ip_address = db.Column(db.String(45), nullable=True)
    usb_port = db.Column(db.String(20), nullable=True)
    status = db.Column(db.String(20), default="offline", nullable=False)
    last_heartbeat = db.Column(db.DateTime, nullable=True)
    location = db.Column(db.String(100), nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)


class FaceTemplate(db.Model):
    """One enrolled face sample. Several rows together are a worker's template.

    face_embedding holds the normalised crop itself: a 200x200 grayscale,
    histogram-equalised image as raw bytes, so exactly 40,000 bytes per row.
    face_engine encodes and decodes it, and trains the LBPH recognizer from
    every row in this table.

    quality_score is the Laplacian variance of the crop - a blur measure, where
    a sharp face scores in the hundreds and a blurred one near zero.

    Three to five samples per worker, taken with small changes of angle and
    expression, matches far more reliably than one.
    """
    __tablename__ = "face_templates"

    face_id = db.Column(db.Integer, primary_key=True)
    worker_id = db.Column(db.Integer, db.ForeignKey("workers.id"), nullable=False)
    face_embedding = db.Column(db.LargeBinary, nullable=False)
    algorithm = db.Column(db.String(30), default="LBPH", nullable=False)
    sample_index = db.Column(db.Integer, default=1, nullable=False)
    reference_image_path = db.Column(db.String(255), nullable=True)
    quality_score = db.Column(db.Float, nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    updated_at = db.Column(db.DateTime, nullable=True)


class BiometricTransaction(db.Model):
    """Every verification attempt, accepted or refused.

    This is the evidence base for accuracy: because each attempt stores its
    score, the threshold in force and the reason, false accepts and false
    rejects can be counted from the table rather than estimated.

    Examples:
        accepted:  transaction_type "face_verify_in",  success True,
                   match_score 71.79, threshold_used 35.0
        refused:   success False, match_score 17.4,
                   error_message "face_did_not_match"
        the fraud case: error_message "face_matched_another_worker" - the face
                   at the camera belongs to a different enrolled worker
    """
    __tablename__ = "biometric_transactions"

    transaction_id = db.Column(db.Integer, primary_key=True)
    device_id = db.Column(db.Integer, db.ForeignKey("biometric_devices.device_id"), nullable=True)
    worker_id = db.Column(db.Integer, db.ForeignKey("workers.id"), nullable=True)
    transaction_type = db.Column(db.String(30), nullable=False)
    modality = db.Column(db.String(20), default="face", nullable=False)
    success = db.Column(db.Boolean, default=False, nullable=False)
    match_score = db.Column(db.Float, nullable=True)
    threshold_used = db.Column(db.Float, nullable=True)
    error_message = db.Column(db.Text, nullable=True)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)


class CCTVRecording(db.Model):
    """A stored video clip.

    Clips are recorded around events rather than continuously - continuous
    capture fills a Raspberry Pi's SD card in hours, while a few seconds either
    side of a punch is what a supervisor actually reviews.

    trigger_type says why it exists: "attendance_in", "attendance_out" or
    "manual". attendance_id links the clip to the session it belongs to, so the
    Attendance page can offer a play button on the row.
    """

    __tablename__ = "cctv_recordings"

    recording_id = db.Column(db.Integer, primary_key=True)
    camera_id = db.Column(db.Integer, db.ForeignKey("cctv_feeds.feed_id"), nullable=True)
    attendance_id = db.Column(db.Integer, db.ForeignKey("attendance.attendance_id"), nullable=True)
    trigger_type = db.Column(db.String(20), default="manual", nullable=False)
    recording_path = db.Column(db.String(255), nullable=False)
    start_time = db.Column(db.DateTime, nullable=False)
    end_time = db.Column(db.DateTime, nullable=True)
    duration_seconds = db.Column(db.Float, nullable=True)
    file_size_bytes = db.Column(db.BigInteger, nullable=True)
    storage_location = db.Column(db.String(20), default="local", nullable=False)
    cloud_url = db.Column(db.String(500), nullable=True)
    uploaded_to_cloud = db.Column(db.Boolean, default=False, nullable=False)
    uploaded_at = db.Column(db.DateTime, nullable=True)


class EventSnapshot(db.Model):
    """The still photo captured at a clock-in or clock-out.

    file_path is relative to the project root, e.g. "captures/0001_20260828_071205.jpg".
    The frame is saved clean - the face and motion boxes drawn on the live view
    are never burned into the stored image.

    cloud_url is filled once the file reaches Firebase; until then it is null
    and the local path is what the UI serves.
    """

    __tablename__ = "event_snapshots"

    snapshot_id = db.Column(db.Integer, primary_key=True)
    attendance_id = db.Column(db.Integer, db.ForeignKey("attendance.attendance_id"), nullable=False)
    camera_id = db.Column(db.Integer, db.ForeignKey("cctv_feeds.feed_id"), nullable=True)
    snapshot_type = db.Column(db.String(20), default="photo", nullable=False)
    file_path = db.Column(db.String(255), nullable=False)
    cloud_url = db.Column(db.String(500), nullable=True)
    captured_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)


class OfflineSyncQueue(db.Model):
    """Work that could not reach the cloud yet.

    A remote farm loses its link regularly, so an upload that fails must not
    lose the record. sync_engine enqueues the snapshot here and retries later,
    up to MAX_RETRIES.

    Example payload for operation_type "snapshot_upload":
        {"local_path": "captures/0001_20260828_071205.jpg",
         "snapshot_id": 42, "reason": "not_configured"}
    """

    __tablename__ = "offline_sync_queue"

    sync_id = db.Column(db.Integer, primary_key=True)
    device_id = db.Column(db.Integer, db.ForeignKey("biometric_devices.device_id"), nullable=True)
    worker_id = db.Column(db.Integer, db.ForeignKey("workers.id"), nullable=True)
    operation_type = db.Column(db.String(50), nullable=False)
    payload = db.Column(db.Text, nullable=False)
    sync_status = db.Column(db.String(20), default="pending", nullable=False)
    retry_count = db.Column(db.Integer, default=0, nullable=False)
    last_error = db.Column(db.Text, nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    synced_at = db.Column(db.DateTime, nullable=True)


class CloudSyncMetadata(db.Model):
    """Per-record cloud state: one row per (table, record) pair.

    Answers "has this particular snapshot reached the cloud?" without scanning
    the queue. cloud_status is "pending" or "synced", and cloud_record_id holds
    the public URL once uploaded.
    """

    __tablename__ = "cloud_sync_metadata"

    sync_id = db.Column(db.Integer, primary_key=True)
    table_name = db.Column(db.String(50), nullable=False)
    record_id = db.Column(db.Integer, nullable=False)
    cloud_status = db.Column(db.String(20), default="pending", nullable=False)
    cloud_record_id = db.Column(db.String(100), nullable=True)
    last_sync_attempt = db.Column(db.DateTime, nullable=True)
    synced_at = db.Column(db.DateTime, nullable=True)

    __table_args__ = (
        db.UniqueConstraint("table_name", "record_id", name="uq_cloud_sync_table_record"),
    )


class DailyAttendanceSummary(db.Model):
    """One row per worker per day: the aggregate payroll reads.

    Rebuilt by payroll_engine.rebuild_day after every punch, and on demand from
    the Attendance page. Only CLOSED sessions contribute hours, so a worker
    still clocked in shows total_hours 0 with sessions_count 1.

    Example - in at 07:30, out at 17:30, with an 8 hour standard day and a
    07:00 shift start:
        total_hours 10.0, overtime_hours 2.0, late_minutes 30
    """

    __tablename__ = "daily_attendance_summary"

    summary_id = db.Column(db.Integer, primary_key=True)
    worker_id = db.Column(db.Integer, db.ForeignKey("workers.id"), nullable=False)
    summary_date = db.Column(db.Date, nullable=False)
    check_in_time = db.Column(db.Time, nullable=True)
    check_out_time = db.Column(db.Time, nullable=True)
    total_hours = db.Column(db.Float, nullable=True)
    overtime_hours = db.Column(db.Float, default=0.0, nullable=False)
    sessions_count = db.Column(db.Integer, default=0, nullable=False)
    late_minutes = db.Column(db.Integer, default=0, nullable=False)
    early_departure_minutes = db.Column(db.Integer, default=0, nullable=False)
    verified_by_cctv = db.Column(db.Boolean, default=False, nullable=False)
    verified_by_face = db.Column(db.Boolean, default=False, nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    __table_args__ = (
        db.UniqueConstraint("worker_id", "summary_date", name="uq_daily_attendance_worker_day"),
    )


class HardwareHealthLog(db.Model):
    """Camera probes and failures.

    Written when a feed is tested, when the whole fleet is health-checked, and
    whenever the attendance camera cannot be opened during a punch or an
    enrolment. On a farm with solar-powered gate cameras this is how a device
    that died overnight gets noticed in the morning, rather than when footage
    is finally needed.

    Example: device_label "North Gate IP Camera", status "offline",
    error_code "open_failed", response_time_ms 3120.
    """

    __tablename__ = "hardware_health_logs"

    log_id = db.Column(db.Integer, primary_key=True)
    device_type = db.Column(db.String(30), nullable=False)
    device_id = db.Column(db.Integer, nullable=False)
    device_label = db.Column(db.String(120), nullable=True)
    status = db.Column(db.String(20), default="offline", nullable=False)
    error_code = db.Column(db.String(50), nullable=True)
    error_message = db.Column(db.Text, nullable=True)
    response_time_ms = db.Column(db.Integer, nullable=True)
    logged_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
